config/routes.rb
Rails.application.routes.draw do
  root to: "static_pages#splash"

  resources :packages, only: [:index, :show]
  resources :users, only: [:new, :create, :show] do
    resources :cubbies, only: [:new, :create]
  end
  resources :subscriptions, only: [:create, :show, :index]

  resources :charges, only: [:new, :create]


  namespace :admin do
    get "/dashboard", to: "users#show"
    get "/price_comparison", to: "price_comparison#index"
    resources :fulfillments, only: [:index, :show, :update]
  end

  get "/login", to: "sessions#new"
  post "/login", to: "internal_sessions#create"
  delete "/logout", to: "sessions#destroy"

  get "/dashboard", to: "users#show"

  get "/auth/github", as: :github_login
  get "/auth/github/callback", to: "external_sessions#create"

  namespace :api do
    namespace :v1 do
      get "/price-comparison/:query", to: "price_comparison#index"
      get "/redemptions", to: "redemptions#create"
    end
  end
end

app/models/fulfillment.rb
class Fulfillment < ApplicationRecord
  belongs_to :subscription

  validates :subscription, presence: true
  validates :week, uniqueness: {scope: :subscription_id }, presence: true, case_sensitive: false

  def user
    self.subscription.user
  end
end

app/controllers/admin/fulfillments_controller.rb
class Admin::FulfillmentsController < Admin::BaseController

  def index
    @fulfillments = Fulfillment.all
    dropdown_options
  end

  def update
    fulfillment = Fulfillment.find(params[:id])
    fulfillment.update(fulfilled?: true)
    redirect_to admin_fulfillments_path
  end

  private
  def dropdown_options
    @modules = Subscription.fulfillment_dropdown_options
    @weeks = ["All Weeks", "1", "2", "3", "4", "5", "6"]
    @users = User.fulfillment_dropdown_options
    @status = ["All", "Pending", "Complete"]
  end

end

app/views/admin/fulfillments/index.html.erb
<h4>Pending Fulfillments</h4>

<%= render "shared/fulfillment_filters" %>

  <table id="pending-fulfillments" class="table table-hover">
    <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>email</th>
      <th>Cubby</th>
      <th>Module</th>
      <th>Week</th>
      <th>Status</th>
      <th></th>
    </tr>
  </thead>

  <tbody class="allFulfillments">
    <% @fulfillments.each do |fulfillment| %>
      <tr class="fulfillment" data-id=<%= fulfillment.id %> id="sub-id-<%= fulfillment.subscription.id %>-week-<%= fulfillment.week %>">
        <td class="first_name"><%= fulfillment.user.first_name %></td>
        <td class="last_name"><%= fulfillment.user.last_name %></td>
        <td class="email"><%= fulfillment.user.email %></td>
        <td class="cubby_location">Cubby Location</td>
        <td class="mod"><%= fulfillment.subscription.mod %></td>
        <td class="week"><%= fulfillment.week %></td>
        <td class="status">
        <% if fulfillment.fulfilled? %>
          Complete
        <% else %>
          <%= link_to "Pending", admin_fulfillment_path(id: fulfillment, fulfill: "true"), method: :patch %>
        <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
  </table>