config/routes.rb
Rails.application.routes.draw do
  root to: "static_pages#splash"

  resources :packages, only: [:index, :show]
  resources :users, only: [:new, :create, :show] do
    resources :cubbies, only: [:new, :create]
  end
  resources :subscriptions, only: [:create, :show, :index]

  resources :charges, only: [:new, :create]


  namespace :admin do
    get "/dashboard", to: "users#show"
    get "/price_comparison", to: "price_comparison#index"
    resources :fulfillments, only: [:index, :show, :update]
  end

  get "/login", to: "sessions#new"
  post "/login", to: "internal_sessions#create"
  delete "/logout", to: "sessions#destroy"

  get "/dashboard", to: "users#show"

  get "/auth/github", as: :github_login
  get "/auth/github/callback", to: "external_sessions#create"

  namespace :api do
    namespace :v1 do
      get "/price-comparison/:query", to: "price_comparison#index"
      get "/redemptions", to: "redemptions#create"
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :subscriptions
  has_one :cubby

  has_secure_password validations: false, if: "uid"

  validates :first_name, presence: true
  validates :last_name, presence: true, if: "uid.nil?"
  validates :email, uniqueness: true, presence: true
  validates :email, confirmation: true, if: "uid.nil?", on: :create
  validates :email_confirmation, presence: true, if: "uid.nil?", on: :create
  validates :password, presence: true, confirmation: true, if: "uid.nil?", on: :create
  validates :password_confirmation, presence: true, if: "uid.nil?", on: :create
  validates :role, presence: true
  validates :uid, uniqueness: true, if: "uid"
  validates :oauth_token, presence: true, if: "uid"

  enum role: %w(default admin)

  def self.from_omniauth(auth_info)
    user = find_or_create_by(uid: auth_info[:uid]) do |new_user|
      new_user.uid = auth_info.uid
      new_user.first_name = auth_info.info.name
      new_user.email = auth_info.info.email
      new_user.oauth_token = auth_info.credentials.token
    end
    return user if user.save
  end

  def self.fulfillment_dropdown_options
    pluck(:email).uniq.unshift("All Users")
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  def show
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome To Cubby Stuffers!"
      send_redemption_offer
      redirect_to new_user_cubby_path(@user)
    else
      flash.now[:danger] = @user.errors.full_messages.join(", ")
      render :new
    end
  end

  def show
    @user = current_user
  end

  private
    def user_params
      params.require(:user).permit(:first_name, :last_name,
                                   :email, :email_confirmation,
                                   :password, :password_confirmation,
                                   :phone_number)
    end

    def send_redemption_offer
      RedemptionOfferMailer.offer(current_user).deliver_now
      flash[:success] << " See your email for special offer!"
    end
end

app/views/users/new.html.erb
;<%= form_for @user do |f| %>
  <div class="form-group container">
    <h4>
      <%= f.label :first_name, "First Name" %>
      <span><%= f.text_field :first_name, class: "form-control" %></span>
    </h4>
    <h4>
      <%= f.label :last_name, "Last Name" %>
      <span><%= f.text_field :last_name, class: "form-control" %></span>
    </h4>
    <h4>
      <%= f.label :email, "Email" %>
      <span><%= f.text_field :email, class: "form-control" %></span>
    </h4>
    <h4>
      <%= f.label :email_confirmation, "Email Confirmation" %>
      <span><%= f.text_field :email_confirmation, class: "form-control" %></span>
    </h4>
    <h4>
      <%= f.label :password, "Password" %>
      <span><%= f.password_field :password, class: "form-control" %></span>
    </h4>
    <h4>
      <%= f.label :password_confirmation, "Password Confirmation" %>
      <span><%= f.password_field :password_confirmation, class: "form-control" %></span>
    </h4>
    <h4>
      <%= f.label :phone_number, "Phone Number" %>
      <span><%= f.text_field :phone_number, class: "form-control" %></span>
    </h4>
    <%= f.submit "Create Account", class: "btn btn-default" %>
  </div>
<% end %>

app/views/users/show.html.erb
<h1 class='container text-center'>User Dashboard</h1><br>

<div class="container text-center">
  <p><% if current_user.cubby %>
      Your cubby is currently located at: <%= current_user.cubby.display_location %>
    <% else %>
      You still need a cubby! <%= link_to "Sign up now!", new_user_cubby_path(current_user) %>
    <% end %>
  <p><%= link_to "Your Subscriptions", subscriptions_path, class: "btn btn-primary" %></p>
</div>