config/routes.rb
Rails.application.routes.draw do
  root to: "static_pages#splash"

  resources :packages, only: [:index, :show]
  resources :users, only: [:new, :create, :show] do
    resources :cubbies, only: [:new, :create]
  end
  resources :subscriptions, only: [:create, :show, :index]

  resources :charges, only: [:new, :create]


  namespace :admin do
    get "/dashboard", to: "users#show"
    get "/price_comparison", to: "price_comparison#index"
    resources :fulfillments, only: [:index, :show, :update]
  end

  get "/login", to: "sessions#new"
  post "/login", to: "internal_sessions#create"
  delete "/logout", to: "sessions#destroy"

  get "/dashboard", to: "users#show"

  get "/auth/github", as: :github_login
  get "/auth/github/callback", to: "external_sessions#create"

  namespace :api do
    namespace :v1 do
      get "/price-comparison/:query", to: "price_comparison#index"
      get "/redemptions", to: "redemptions#create"
    end
  end
end

app/views/shared/_flash.html.erb
<div class="container">
  <% flash.each do |type, message| %>
    <div class="alert alert-<%= type %>" role="alert"><%= sanitize(message) %></div>
  <% end %>
</div>

app/views/shared/_fulfillment_filters.html.erb
<div class="col-md-6">
  <div class="text-center all_filters">
    <span class="filter-padding"><strong>Filters:</strong></span>
    Module <%= select("fulfillment", "filter_module", @modules, selected: "All Modules") %>
    Week <%= select("fulfillment", "filter_week", @weeks, selected: "All Weeks") %>
    User <%= select("fulfillment", "filter_user", @users, selected: "All Users") %>
    Status <%= select("fulfillment", "filter_status", @status, selected: "All") %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div id="logo-container">
        <a class="navbar-brand navbar-left" href='/'> <%= image_tag('cubbystufferslogo.png', id: "logo-image") %></a>
      </div>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right" id="navbar-links">
        <li><%= link_to "Packages", packages_path %></li>
        <li><%= link_to "Login", login_path unless current_user %></li>
        <%= render "shared/user_dropdown" %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_user_dropdown.html.erb
<% if current_user %>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.first_name if current_user %><span class="caret"></span></a>
  <ul class="dropdown-menu">
    <% if current_user %>
    <li><%= link_to "Dashboard", "/dashboard" %></li>
    <% if current_admin? %>
    <li><%= link_to "Admin Dashboard", "/admin/dashboard" %></li>
    <% end %>
    <li><%= link_to "Logout", "/logout", method: :delete %></li>
    <% end %>
  </ul>
</li>
<% end %>