config/routes.rb
Rails.application.routes.draw do
  root to: "static_pages#splash"

  resources :packages, only: [:index, :show]
  resources :users, only: [:new, :create, :show] do
    resources :cubbies, only: [:new, :create]
  end
  resources :subscriptions, only: [:create, :show, :index]

  resources :charges, only: [:new, :create]


  namespace :admin do
    get "/dashboard", to: "users#show"
    get "/price_comparison", to: "price_comparison#index"
    resources :fulfillments, only: [:index, :show, :update]
  end

  get "/login", to: "sessions#new"
  post "/login", to: "internal_sessions#create"
  delete "/logout", to: "sessions#destroy"

  get "/dashboard", to: "users#show"

  get "/auth/github", as: :github_login
  get "/auth/github/callback", to: "external_sessions#create"

  namespace :api do
    namespace :v1 do
      get "/price-comparison/:query", to: "price_comparison#index"
      get "/redemptions", to: "redemptions#create"
    end
  end
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user
  belongs_to :package
  has_many :fulfillments

  validates :user_id, presence: true
  validates :package_id, presence: true
  validates :price, presence: true
  validates :mod, presence: true
  validates :weeks, presence: true

  def week_array
    (1..weeks).to_a
  end

  def self.fulfillment_dropdown_options
    pluck(:mod).uniq.unshift("All Modules")
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  def show
    @subscription = Subscription.find(params[:id])
  end

  def index
    @subscriptions = current_user.subscriptions
  end
end

app/views/subscriptions/index.html.erb
<h1 class='container'>Subscriptions</h1>
<div class="container">
<table class="table table-hover">
  <thead>
  <tr>
    <th>Id</th>
    <th>Module</th>
    <th>Weeks</th>
    <th>Price</th>
  </tr>
  </thead>

  <tbody>
    <% @subscriptions.each do |subscription| %>
    <tr>
      <td><%= link_to subscription.id, subscription_path(subscription) %></td>
      <td><%= subscription.mod %></td>
      <td><%= subscription.week_array.join(", ") %></td>
      <td><%= number_to_currency(subscription.price) %></td>
    </tr>
  <% end %>
</tbody>
</table>
</div>

app/views/subscriptions/show.html.erb
<h1 class='container text-center'><%= @subscription.package.name %> - <%= @subscription.mod %></h1>

<div class='container'>
  <p>Id: <%= @subscription.id %></p>
  <p>Price: <%= @subscription.price %></p>
  <p>Module: <%= @subscription.mod %></p>
  <p>Weeks: <%= @subscription.weeks %></p>
  <p>Package: <%= link_to @subscription.package.name, package_path(@subscription.package) %></p>
  <p>Package Items: <%= @subscription.package.items.map(&:name).join(", ") %></p>
  <p>Fulfillments:</p><br>
  <div class="container">
  <table class="table table-hover">
    <thead>
    <tr>
      <th>Week</th>
      <th>Status</th>
    </tr>
    </thead>

    <tbody>
      <% @subscription.fulfillments.each do |fulfillment| %>
      <tr>
        <td><%= fulfillment.week %></td>
        <td><% if fulfillment.fulfilled? %>
            Fulfilled
            <% else %>
            Pending
            <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
  </table>
  </div>
</div>